spring:
  datasource:
    url: jdbc:mysql://120.46.151.254:13306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  redis:
    host: 120.46.151.254 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 16379 # Redis服务器连接端口
    password: '!1Qaz@2Wsx'# Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）

logging:
  level:
    root: info
    com.macro.mall: debug